export { default as HomePage } from './HomePage/HomePage'
export { default as AboutPage } from './AboutPage/AboutPage'
export { default as ArtPage } from './AboutPage/AboutPage'
export { default as CodePage } from './CodePage/CodePage'
export { default as DesignPage } from './DesignPage/DesignPage'